[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
crossbeam-utils = "0.8.16"
image = "0.24.7"
log = "0.4.20"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
